name: LavaBoat
main: me.Justyce.LavaBoat
author: _Justyce_
version: 0.8.2
commands:
  lb:
    description : allow to add or remove a world for the multiworld support
    usage: /<command> <enable|disable|walk>
permissions:
  lb.*:
    description: allow to use boat, minecarts, pigs and walk on lava
  lb.minecarts:
    description: allow to use minecarts
  lb.boats:
    description: allow to use boats
  lb.walk:
    description: allow to walk on lava