name: LavaBoat
main: org.lavaboat.LavaBoat
author: _Justyce_
version: 0.9
commands:
  lb:
    description : allow to add or remove a world for the multiworld support
    usage: /<command> <enable|disable|walk>
permissions:
  lb.*:
    description: allow to use all features of this plugin
  lb.minecarts:
    description: allow to use minecarts
  lb.boats:
    description: allow to use boats
  lb.walk:
    description: allow to walk on lava
  lb.world:
    description: allow to disable or enable this plugin in your world